{
    "name": "Hospital Management",
    "version": "19.0.1.0.0",
    "category": "Hospital",
    "summary": "Hospital management",
    "author": "Igor Bagriy",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "data/doctor_category_data.xml",
        "views/hr_hospital_doctor_views.xml",
        "views/hospital_doctor_category_views.xml",
        "views/hospital_doctor_history_views.xml",
        "views/hr_hospital_patient_views.xml",
        "views/hr_hospital_disease_views.xml",
        "views/hr_hospital_visit_views.xml",
        "wizard/mass_reassign_doctor_wizard_views.xml",
        "wizard/visit_report_wizard_views.xml",
        "views/hr_hospital_menus.xml",
    ],
    "demo": [
        "demo/hr_hospital_doctor_demo.xml",
        "demo/hr_hospital_patient_demo.xml",
        "demo/hr_hospital_disease_demo.xml",
        "demo/hospital_doctor_history_demo.xml",
        "demo/hr_hospital_visit_demo.xml",
    ],
    "installable": True,
    "application": True,
    'images':
        ['static/description/icon.png'],
}
